version: '3.8'
services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=
      - ADMINS=184374602,5499607808
      - DB_URL=postgresql://user:password@db:5432/dbname
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: